# The channel name(s) to check for subscription/follows.
channels:
  - name: kixstar
    subscribe:
      enabled: true
      rank: kixsub
      commands:
        - "broadcast %name% has subscribed to %channel%!"
      revoke-commands: []
    follow:
      enabled: false
  - name: thegodlynoob
    subscribe:
      enabled: true
      rank: godlysub
      commands:
        - "broadcast %name% has subscribed to %channel%!"
      revoke-commands: []
    follow:
      enabled: false

upgrades:
  - rank: ubersub
    threshold: 2

# The client ID given by Twitch.
client-id: required

# The client secret given by Twitch. Remember not to tell anyone this!
client-secret: required

# Port to host the HTTP server on
server-port: 8080

# Redirect URI for Twitch authentication. This has to be set as the same as Twitch
redirect-uri: http://localhost:8080

# How many minutes it takes for twitch sync URLs to expire.
expiry-time: 10

# Note that these messages are sent by the web server and use HTML, not chat formatting.
messages:
  subscription:
    no-subscription-program: "The channel does not have a subscription program set up."
    success: "Successfully set up Twitch Sync."
  follow:
    success: "You have successfully received the Twitch following rewards."
  success-both: "You have received both the following and subscription rewards."

  # If you have subscription or following rewards disabled you might want to change this
  # to say "You are not following" or "You are not subscribed" to make it clear
  # that it's only possible to get rewards for one thing
  not-both: "You are not subscribed to any of the channels."
  already-done: "You have already redeemed subscription and/or follow rewards."

  state-not-found: "This link has either expired, or already been used."
  player-not-found: "We cannot find you on the server. Are you online?"
  invalid-url: "The URL is invalid"
  unknown-error: "An unknown error occurred. Please try again."

# revoke subscriber/follow rewards every X days
# this will remove the rank and run revoke-commands
revoke-interval-days: 1

# Enable debugging information.
# If you encounter an unexpected error please enable this
# and send the results to the dev!
debug-mode: false
